[tool.mypy]
strict = true
no_implicit_reexport = false
allow_incomplete_defs = true
allow_untyped_defs = true
warn_return_any = false
disallow_untyped_calls = false
ignore_missing_imports = true

[tool.isort]
profile = "black"
add_imports = ["from __future__ import annotations"]
